from __future__ import annotations
from typing import Protocol, Optional


class JobRepository(Protocol):
    def enqueue(self, job_id: str, owner_user_id: str, job_type: str, payload: dict, max_attempts: int = 3) -> None: ...
    def get(self, job_id: str) -> Optional[dict]: ...
    def claim_next(self, job_type: str = "") -> Optional[dict]: ...
    def complete(self, job_id: str, result: dict) -> None: ...
    def fail(self, job_id: str, reason: str) -> None: ...
    def cancel(self, job_id: str, owner_user_id: str) -> None: ...
    def list_events(self, owner_user_id: str) -> list[dict]: ...
    def get_event(self, event_id: str, owner_user_id: str) -> Optional[dict]: ...
    def claim_event(self, worker_id: str, lease_duration_seconds: int) -> Optional[dict]: ...
    def release_event(self, event_id: str) -> None: ...
    def ack_event(self, event_id: str) -> None: ...
