import os
import sys
import json
import subprocess
from pathlib import Path

def find_py_files(root: Path):
    """Recursively collect all .py files under the given root directory."""
    return [p for p in root.rglob('*.py') if p.is_file()]

def compile_check(file_path: Path):
    """Run `python -m py_compile` on a file.
    Returns ``None`` if compilation succeeds, otherwise returns the error message.
    """
    try:
        subprocess.check_output([sys.executable, '-m', 'py_compile', str(file_path)], stderr=subprocess.STDOUT)
        return None
    except subprocess.CalledProcessError as e:
        return e.output.decode('utf-8').strip()

def scan_markers(file_path: Path, markers=('TODO', 'FIXME', 'BUG', 'raise NotImplementedError')):
    """Search a file for common development markers.
    Returns a list of tuples: (line_number, marker, snippet).
    """
    results = []
    try:
        lines = file_path.read_text(encoding='utf-8').splitlines()
    except Exception:
        return results
    for i, line in enumerate(lines, start=1):
        for marker in markers:
            if marker in line:
                results.append((i, marker, line.strip()))
    return results

def main():
    # Repository root (project folder containing this script)
    repo_root = Path(__file__).resolve().parent.parent
    report_path = repo_root / 'reports' / 'module_analysis_report.md'
    report_path.parent.mkdir(parents=True, exist_ok=True)

    py_files = find_py_files(repo_root)
    syntax_errors = []
    marker_items = []

    for py in py_files:
        err = compile_check(py)
        if err:
            syntax_errors.append((py, err))
        markers = scan_markers(py)
        for line_no, marker, snippet in markers:
            marker_items.append((py, line_no, marker, snippet))

    # Write the markdown report
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write('# Module Analysis Report\n\n')
        f.write('Generated by `scripts/analyze_modules.py` on ' + subprocess.getoutput('date') + '\n\n')
        f.write('## Syntax Errors\n')
        if syntax_errors:
            for py, err in syntax_errors:
                f.write(f'- **{py.relative_to(repo_root)}**: {err}\n')
        else:
            f.write('No syntax errors detected.\n')
        f.write('\n## TODO / FIXME / BUG Markers\n')
        if marker_items:
            for py, line_no, marker, snippet in marker_items:
                f.write(f'- **{py.relative_to(repo_root)}:{line_no}** `{marker}`: {snippet}\n')
        else:
            f.write('No TODO/FIXME/BUG markers found.\n')
        f.write('\n---\n')
        f.write('**Recommendations**:\n')
        if syntax_errors:
            f.write('- Fix the listed syntax errors.\n')
        if marker_items:
            f.write('- Review each TODO/FIXME/BUG entry and implement or resolve them.\n')
        f.write('- Consider adding type hints and running a linter for further improvements.\n')

    print(f'Report written to {report_path}')

if __name__ == "__main__":
    main()
